/* Wiedweg – 8 Etappen, ca. 117 km, Qualitätsweg Wanderbares Deutschland */
var DATA_WANDERN_WIEDWEG=[
  {t:'Wiedweg 01. Etappe Hachenburg \u2013 Linden',km:'10',sw:'mittel',d:'Hachenburger Stadtwald, Gr\u00e4bersberg, Wiedquelle',
   url:'https://www.westerwald.info/d/wiedweg-01-etappe-hachenburg-linden/',
   gpx:'https://www.tourenplaner-rheinland-pfalz.de/de/download.tour.gpx?i=804990301&project=oar-rlp',
   stats:{duration:'2,5 h',ascent:'182 hm',descent:'46 hm',highPoint:'524 m',lowPoint:'350 m'},
   description:'Die Auftaktetappe f\u00fchrt vom Barockschloss Hachenburg durch den Hachenburger Stadtwald zum Aussichtsturm auf dem Gr\u00e4bersberg (513 m) mit einem wunderbaren Panoramablick \u00fcber den Westerwald. Von dort geht es weiter nach Linden zur Wiedquelle, die unter den Wurzeln einer mehrere hundert Jahre alten Buche entspringt.',
   directions:{byCar:'\u00dcber die A3 bis Abfahrt Montabaur, \u00fcber die B255 und B8 nach Hachenburg.',byPublicTransport:'Buslinie 115 bis Hachenburg.'},
   safetyNotes:'Bei widrigen Wetterverh\u00e4ltnissen kann es bei naturnahen Wegen zu matschigen und rutschigen Passagen kommen. Immer eine Wanderkarte mitnehmen oder die kostenlose App \u201eRheinland-Pfalz erleben\u201c herunterladen.',
   equipment:'Festes Schuhwerk und witterungsangepasste Kleidung. Ausreichend Fl\u00fcssigkeit mitnehmen.',
   tips:'Barockschloss Hachenburg \u00b7 Hachenburger Brauerei \u00b7 Aussichtsturm Gr\u00e4bersberg (513 m) \u00b7 Wiedquelle bei Linden',
   literature:'Topografische Karte 1:25.000 \u201eFerienland Westerwald Blatt 1\u201c. Festes Schuhwerk empfohlen!',
   startPoint:'Hachenburg, Barockschloss',
   endPoint:'Linden, Wiedquelle'},
  {t:'Wiedweg 02. Etappe Linden \u2013 H\u00f6chstenbach',km:'16',sw:'mittel',d:'Dreifelder Weiher, Oberes Wiedtal, Skulpturenpark',
   url:'https://www.westerwald.info/d/wiedweg-02-etappe-linden-hoechstenbach/',
   gpx:'https://www.tourenplaner-rheinland-pfalz.de/de/download.tour.gpx?i=38077762&project=oar-rlp',
   stats:{duration:'3,8 h',ascent:'54 hm',descent:'228 hm',highPoint:'466 m',lowPoint:'290 m'},
   description:'Von der Wiedquelle begleitest du die noch junge Wied auf schmalen, naturnahen Pfaden nach Dreifelden mit der \u00e4ltesten Steinkirche im Westerwald (Dreifaltigkeitskirche). Am Dreifelder Weiher, dem gr\u00f6\u00dften Gew\u00e4sser der Westerwaldsteig Seenplatte, l\u00e4dt die Landschaft zum Verweilen ein. Durch das Naturschutzgebiet Oberes Wiedtal und den Skulpturenpark Steinebach/Wied geht es nach H\u00f6chstenbach.',
   directions:{byCar:'L303 nach Linden. Parkplatz: Wiedbachhalle, Waldstra\u00dfe 12 oder Friedhof Linden (Ende der Waldstra\u00dfe).',byPublicTransport:'Buslinie 115 bis Hachenburg, dann Taxi nach Linden zur Wiedquelle.'},
   safetyNotes:'Bei widrigen Wetterverh\u00e4ltnissen kann es bei naturnahen Wegen zu matschigen und rutschigen Passagen kommen.',
   equipment:'Festes Schuhwerk empfohlen. Witterungsangepasste Kleidung. Ausreichend Fl\u00fcssigkeit mitnehmen.',
   tips:'Dreifaltigkeitskirche Dreifelden (\u00e4lteste Steinkirche im Westerwald) \u00b7 Dreifelder Weiher (Strandbad, gr\u00f6\u00dftes Gew\u00e4sser der Seenplatte) \u00b7 Skulpturenpark Steinebach/Wied \u00b7 Naturschutzgebiet Oberes Wiedtal',
   literature:'Topografische Karte 1:25.000 \u201eFerienland Westerwald Blatt 1\u201c.',
   startPoint:'Linden, Wiedquelle (N 50\u00b0 36\u2032 16.1\u2033 | O 7\u00b0 51\u2032 11.0\u2033)',
   endPoint:'H\u00f6chstenbach, Koblenzer Stra\u00dfe 3'},
  {t:'Wiedweg 03. Etappe H\u00f6chstenbach \u2013 Altenkirchen',km:'16',sw:'mittel',d:'Krambergsm\u00fchle, Michelbacher M\u00fchle, Bismarckturm',
   url:'https://www.westerwald.info/d/wiedweg-03-etappe-hoechstenbach-altenkirchen/',
   gpx:'https://www.tourenplaner-rheinland-pfalz.de/de/download.tour.gpx?i=2892805&project=oar-rlp',
   stats:{duration:'5,0 h',ascent:'233 hm',descent:'299 hm',highPoint:'380 m',lowPoint:'200 m'},
   description:'Von H\u00f6chstenbach mit seiner evangelischen Pfarrkirche (Wandmalereien aus dem 13. Jh.) f\u00fchrt der Weg vorbei an der Krambergsm\u00fchle und dem fr\u00fcheren Hofgut Farrenau bei Mudenbach. Durch die Orte Borod, Ingelbach und Widderstein gelangst du nach Michelbach, wo noch heute viele Tonnen Getreide gemahlen werden. Durch das Naturschutzgebiet Im Dorm geht es hinauf zum Johannisberg mit dem 14 m hohen Bismarckturm und herrlichem Ausblick auf Altenkirchen.',
   directions:{byCar:'B8 bis H\u00f6chstenbach.',byPublicTransport:'Busverbindungen nach H\u00f6chstenbach \u00fcber Hachenburg.'},
   safetyNotes:'Bei widrigen Wetterverh\u00e4ltnissen kann es zu matschigen und rutschigen Passagen kommen.',
   equipment:'Festes Schuhwerk und witterungsangepasste Kleidung. Ausreichend Fl\u00fcssigkeit mitnehmen.',
   tips:'Evangelische Pfarrkirche H\u00f6chstenbach (Wandmalereien 13. Jh.) \u00b7 Krambergsm\u00fchle \u00b7 Michelbacher M\u00fchle (aktiver M\u00fchlenbetrieb) \u00b7 Naturschutzgebiet Im Dorm \u00b7 Bismarckturm Johannisberg (14 m, Aussicht auf Altenkirchen)',
   literature:'\u201eWandern im n\u00f6rdlichen Westerwald Blatt 1\u201c, 4. Auflage 2008 (ISBN 978-3-89637-250-5).',
   startPoint:'H\u00f6chstenbach',
   endPoint:'Altenkirchen'},
  {t:'Wiedweg 04. Etappe Altenkirchen \u2013 Oberlahr',km:'16',sw:'leicht',d:'Kreisstadt Altenkirchen, Wiedtal, Lahrer Herrlichkeit',
   url:'https://www.westerwald.info/d/wiedweg-04-etappe-altenkirchen-oberlahr/',
   gpx:'https://www.tourenplaner-rheinland-pfalz.de/de/download.tour.gpx?i=2892824&project=oar-rlp',
   stats:{duration:'5,0 h',ascent:'131 hm',descent:'207 hm',highPoint:'310 m',lowPoint:'180 m'},
   description:'Von der Kreisstadt Altenkirchen f\u00fchrt die Etappe gem\u00fctlich entlang der Wied durch das Wiedtal mit seinen Auenlandschaften. Du erreichst Oberlahr in der \u201eLahrer Herrlichkeit\u201c, einem besonders malerischen Abschnitt des Wiedtals.',
   directions:{byCar:'B8 bis Altenkirchen.',byPublicTransport:'Busverbindungen nach Altenkirchen (Westerwald).'},
   safetyNotes:'Bei widrigen Wetterverh\u00e4ltnissen kann es zu matschigen und rutschigen Passagen kommen.',
   equipment:'Festes Schuhwerk empfohlen. Witterungsangepasste Kleidung.',
   tips:'Kreisstadt Altenkirchen \u00b7 Wiedtal-Auen \u00b7 Lahrer Herrlichkeit',
   literature:'\u201eWandern im n\u00f6rdlichen Westerwald Blatt 1\u201c.',
   startPoint:'Altenkirchen',
   endPoint:'Oberlahr'},
  {t:'Wiedweg 05. Etappe Oberlahr \u2013 Neustadt (Wied)',km:'14',sw:'mittel',d:'Lahrer Herrlichkeit, D\u00f6ttesfeld, Mittelpunkt der Wied',
   url:'https://www.westerwald.info/d/wiedweg-05-etappe-oberlahr-neustadt-wied/',
   gpx:'https://www.tourenplaner-rheinland-pfalz.de/de/download.tour.gpx?i=2892833&project=oar-rlp',
   stats:{duration:'4,5 h',ascent:'317 hm',descent:'341 hm',highPoint:'320 m',lowPoint:'170 m'},
   description:'Diese Etappe f\u00fchrt dich durch die Lahrer Herrlichkeit, einen besonders malerischen Abschnitt des Wiedtals zwischen D\u00f6ttesfeld und Neustadt (Wied). Vom Dorf Eilenberg, dem Mittelpunkt der Wied, sind es je 51 km bis zur Quelle und zur M\u00fcndung.',
   directions:{byCar:'L255 bis Oberlahr.',byPublicTransport:'Busverbindungen nach Oberlahr.'},
   safetyNotes:'Bei widrigen Wetterverh\u00e4ltnissen kann es zu matschigen und rutschigen Passagen kommen.',
   equipment:'Festes Schuhwerk und witterungsangepasste Kleidung. Ausreichend Fl\u00fcssigkeit mitnehmen.',
   tips:'Lahrer Herrlichkeit \u00b7 Pfarrkirche St. Margarita Neustadt (Taufstein 14. Jh.) \u00b7 Eilenberg \u2013 Mittelpunkt der Wied',
   literature:'\u201eNaturpark Rhein-Westerwald Blatt 2 (Nord)\u201c, 5. Auflage 2008 (ISBN 978-3-89637-265-9).',
   startPoint:'Oberlahr',
   endPoint:'Neustadt (Wied), Kirchplatz'},
  {t:'Wiedweg 06. Etappe Neustadt (Wied) \u2013 Ro\u00dfbach/Wied',km:'17',sw:'schwer',d:'Burgruine Altenwied, Wei\u00dfenfelser Ley, FFH-Gebiet',
   url:'https://www.westerwald.info/d/wiedweg-06-etappe-neustadt-wied-rossbach-wied/',
   gpx:'https://www.tourenplaner-rheinland-pfalz.de/de/download.tour.gpx?i=2892843&project=oar-rlp',
   stats:{duration:'5,5 h',ascent:'467 hm',descent:'498 hm',highPoint:'340 m',lowPoint:'130 m'},
   description:'Von Neustadt geht es bergauf und bergab durch den Naturpark Rhein-Westerwald und das FFH-Gebiet \u201eFelsentalwand der Wied\u201c. Nach der Unterquerung der Autobahn wechselt die Strecke die Uferseite und f\u00fchrt hinter Wiedm\u00fchle zur Burgruine Altenwied auf einem Felssporn \u00fcber der Wied. Gemeinsam mit dem WesterwaldSteig leitet der Wiedweg auf die Wei\u00dfenfelser Ley bis nach Ro\u00dfbach.',
   directions:{byCar:'L255 bis Neustadt (Wied).',byPublicTransport:'Busverbindungen nach Neustadt (Wied).'},
   safetyNotes:'Bei widrigen Wetterverh\u00e4ltnissen kann es zu matschigen und rutschigen Passagen kommen. Einige steile und felsige Abschnitte erfordern gute Kondition und trittsicheres Gehen.',
   equipment:'Festes Schuhwerk zwingend erforderlich. Witterungsangepasste Kleidung und ausreichend Fl\u00fcssigkeit.',
   tips:'FFH-Gebiet Felsentalwand der Wied \u00b7 Burgruine Altenwied (f\u00fcnfeckiger Bergfried) \u00b7 Wei\u00dfenfelser Ley \u00b7 Ro\u00dfbacher H\u00e4ubchen (Basaltkuppe)',
   literature:'\u201eNaturpark Rhein-Westerwald Blatt 2 (Nord)\u201c.',
   startPoint:'Neustadt (Wied), Kirchplatz',
   endPoint:'Ro\u00dfbach/Wied'},
  {t:'Wiedweg 07. Etappe Ro\u00dfbach/Wied \u2013 Niederbreitbach',km:'10',sw:'mittel',d:'Kloster Waldbreitbach, Bibelgarten, Claus-Kapelle',
   url:'https://www.westerwald.info/d/wiedweg-07-etappe-rossbach-wied-niederbreitbach/',
   gpx:'https://www.tourenplaner-rheinland-pfalz.de/de/download.tour.gpx?i=2892848&project=oar-rlp',
   stats:{duration:'3,2 h',ascent:'261 hm',descent:'287 hm',highPoint:'300 m',lowPoint:'100 m'},
   description:'Von Ro\u00dfbach f\u00fchrt der Weg ins untere Wiedtal. Hinauf auf den Klosterberg thront das St. Marienhaus der Waldbreitbacher Franziskanerinnen (seit 1861) mit Bibelgarten, Sch\u00f6pfungspfad und Klosterbergterrassen mit wundersch\u00f6ner Aussicht auf das Wiedtal. \u00dcber schmale Serpentinenpfade vom Clausberg geht es hinunter nach Niederbreitbach mit der sehenswerten Claus-Kapelle aus dem 14. Jahrhundert.',
   directions:{byCar:'L255 bis Ro\u00dfbach/Wied.',byPublicTransport:'Busverbindungen \u00fcber Waldbreitbach.'},
   safetyNotes:'Steile Serpentinenpfade vom Clausberg nach Niederbreitbach. Bei N\u00e4sse besonders rutschig. Festes Schuhwerk zwingend erforderlich.',
   equipment:'Festes Schuhwerk zwingend erforderlich. Witterungsangepasste Kleidung und Rucksackverpflegung.',
   tips:'Ro\u00dfbacher H\u00e4ubchen \u00b7 St. Marienhaus Waldbreitbach (Bibelgarten, Sch\u00f6pfungspfad, Kr\u00e4uterkurse) \u00b7 Klosterbergterrassen (Aussicht) \u00b7 Claus-Kapelle Niederbreitbach (14. Jh.)',
   literature:'\u201eNaturpark Rhein-Westerwald Blatt 3 (S\u00fcd)\u201c, 6. Auflage 2008 (ISBN 978-3-89637-266-6).',
   startPoint:'Ro\u00dfbach/Wied',
   endPoint:'Niederbreitbach'},
  {t:'Wiedweg 08. Etappe Niederbreitbach \u2013 Irlich (Neuwied)',km:'19',sw:'mittel',d:'Laubacher Wasserfall, Altwied, Wiedm\u00fcndung am Rhein',
   url:'https://www.westerwald.info/d/wiedweg-08-etappe-niederbreitbach-irlich/',
   gpx:'https://www.tourenplaner-rheinland-pfalz.de/de/download.tour.gpx?i=2892856&project=oar-rlp',
   stats:{duration:'5,7 h',ascent:'326 hm',descent:'364 hm',highPoint:'200 m',lowPoint:'58 m'},
   description:'Die letzte Etappe f\u00fchrt von Niederbreitbach durch das enge Wiedtal \u00fcber Datzeroth, wo es nochmal richtig abenteuerlich wird. Vorbei am Laubacher Wasserfall geht es durch die Ortschaften Altwied und Niederbieber. Schlie\u00dflich erreichst du Neuwied-Irlich, wo die Wied in den Rhein m\u00fcndet \u2013 das feierliche Ziel des gesamten Wiedweges.',
   directions:{byCar:'L255 bis Niederbreitbach.',byPublicTransport:'Busverbindungen \u00fcber Waldbreitbach nach Niederbreitbach. R\u00fcckreise: Ab Neuwied-Irlich mit Bus/Bahn. Keine direkte Anbindung zwischen Neuwied-Irlich und Linden \u2013 Transfer mit Taxi empfohlen.'},
   safetyNotes:'Einige abenteuerliche Passagen bei Datzeroth. Bei widrigen Wetterverh\u00e4ltnissen besondere Vorsicht geboten.',
   equipment:'Festes Schuhwerk und witterungsangepasste Kleidung.',
   tips:'Laubacher Wasserfall \u00b7 Burg Altwied \u00b7 Niederbieber (r\u00f6mische Geschichte) \u00b7 Schlosstheater Neuwied \u00b7 Wiedm\u00fcndung in den Rhein bei Irlich',
   literature:'\u201eNaturpark Rhein-Westerwald Blatt 3 (S\u00fcd)\u201c.',
   startPoint:'Niederbreitbach',
   endPoint:'Neuwied-Irlich, Wiedm\u00fcndung (N 50\u00b0 26\u2032 30.5\u2033 | O 7\u00b0 26\u2032 34.5\u2033)'}
];
